import mongoose from "mongoose";

const userSchema = new mongoose.Schema({
  name: { type: String, required: true },
  personalContact: { type: String, required: true, unique : true },
  employeeID: { type: String, required: true, unique : true },
  dateOfBirth: { type: Date, required: true },
  personalEmail: { type: String, unique: true },
  password: { type: String},
  presentAddress: { type: String, required: true},
  //state //country //pincode //city
  gender: { type: String, enum: ["MALE", "FEMALE", "OTHER"], required: true },
  profileImage: { type: String },
  dateOfJoining: { type: Date, required: true },
  aadhaarNumber: { type: Number, required: true, unique : true },
  qualification: { type: String, },
  maritalStatus: { type: String, enum: ["Single", "Married"], required: true},
  emergencyContact: {type: String},
  spouseName: { type : String},
  childrenCount: {type: String},
  permanentAddress: { type: String},
  officeContact: { type: String, unique : true },
  officeEmail: { type: String },
  PANNumber: { type: String, unique : true},
  department: { type: String, required: true },
  designation: { type: String, required: true },
  jobRole: {type: String},/*array enum*/
  workPlace: { type: String, required: true },
  workSiteDetails: { type: String,},
  client: { type: String, required: true },
  clientID: { type: String, required: true },
  reportingInchargePerson: { type: String },
  repPersonDesignation: { type: String },
  repPersonEmployeeID: { type: String },
  currentSalary: { type: String },
  bankName: { type: String, required: true },
  bankAccountNumber: { type: String, required: true, unique : true },
  IFSCCode: { type: String, required: true },
  bankBranch: { type: String, required: true },
  ESIDetails: { type: String,},
  insuranceDetails: { type: String,},
  PFDetails: { type: String,},
  //teamCount: { type: Number },
  //teamDetails: { type: Array },
  previousDesignation: { type: String },
  previousSalary: { type: String },
  dateOfPromotion: { type: Date },
  dateOfTermination: { type: Date },
  refPerson: { type: String },
  isRefPersonEmployee: { type: String, enum: ["Yes", "No"]},
  refPersonContact: { type: String },
  refPersonEmployeeID: { type: String },
  webrole: {
    type: String,
    enum: ["admin", "manager", "staff", "employee"],
    required: true,
  },
});

const User = mongoose.model("User", userSchema);
export default User;
