import mongoose from "mongoose";

const userSchema = new mongoose.Schema({
  name: { type: String, required: true },
  contactSelf: { type: String, required: true, unique : true },
  contactCompany: { type: String, unique : true },
  address: { type: String, required: true},
  addressPermanent: { type: String, required: true},
  aadhaarNumber: { type: Number, required: true, unique : true },
  gender: { type: String, enum: ["MALE", "FEMALE", "OTHER"], required: true },
  employeeID: { type: String, required: true, unique : true },
  emailPersonal: { type: String, unique: true },
  emailOffice: { type: String },
  password: { type: String},
  PANNumber: { type: String, unique : true},
  dateOfBirth: { type: Date, required: true },
  dateOfJoining: { type: Date, required: true },
  profileImage: { type: String },
  department: { type: String, required: true },
  designation: { type: String, required: true },
  service: {type: String},
  webrole: {
    type: String,
    enum: ["admin", "manager", "staff", "employee"],
    required: true,
  },
  workPlace: { type: String, required: true },
  siteDetails: { type: String,},
  maritalStatus: { type: String},
  spouseName: { type : String},
  childrenCount: {type: String},
  emergencyContact: {type: String},
  client: { type: String, required: true },
  reportingInchargePerson: { type: String },
  repPersonDesignation: { type: String },
  repPersonEmployeeID: { type: String },
  currentSalary: { type: String },
  bankName: { type: String, required: true },
  bankAccountNumber: { type: String, required: true, unique : true },
  IFSCCode: { type: String, required: true },
  bankBranch: { type: String, required: true },
  ESICDetails: { type: String,},
  insuranceDetails: { type: String,},
  PFDetails: { type: String,},
  teamCount: { type: Number },
  teamDetails: { type: Array },
  previousDesignation: { type: String },
  previousSalary: { type: String },
  dateOfPromotion: { type: Date },
  dateOfTermination: { type: Date },
  refPerson: { type: String },
  isRefPersonEmployee: { type: String, enum: ["Yes", "No"]},
  refPersonContact: { type: String },
  refPersonEmployeeID: { type: String },
});

const User = mongoose.model("User", userSchema);
export default User;
